### PR TITLE
simplify design

### LINKED ISSUE #10: Combine multiple ignore files
I expect an API like this:

```go
gitignore.Combine(
    gitignore.FromFile("./.gitignore"),
    gitignore.FromFile("./to/.gitignore"),
    gitignore.FromFile("./to/your/.gitignore"),
)
```

### PR DESCRIPTION
**Pull request by septs**
Convenient preset rules

```go
gitignore.Combine(
    gitignore.FromLines(".", []string{".DS_Store", "License.nfo"}),
    gitignore.FromLines("./foo", []string{"*.dng"}),
    gitignore.FromLines("./foo/bar", []string{"*.log"}),
    // ... user ignore patterns ...
)
```

closes https://github.com/monochromegane/go-gitignore/issues/10

### CODE REVIEW

**Comment by septs** [comment]
I think the method name can be shortened:
| Original method name | New method name | Actual use |
| -- | -- | -- |
| `NewGitIgnore` | `FromFile` | `gitignore.FromFile` |
| `NewGitIgnoreFromReader` | `FromReader` | `gitignore.FromReader` |
| `NewGitIgnoreFromLines` | `FromLines` | `gitignore.FromLines` |

**Comment by septs** [comment]
New feature:

```go
gitignore.NewFromFile("to/your/.ignore", "to", "your")
// eq
gitignore.NewFromFile("to/your/.ignore", filepath.Join("to", "your"))
```

**Comment by septs** [comment]
@monochromegane

**Comment by septs** [comment]
@monochromegane

**Comment by septs** [comment]
@monochromegane

**Comment by monochromegane** [comment]
Thank you for your suggestion.
But I have no plans to change the interface so far.

**Pull request closed without merging**
