### PR TITLE
add dummy ignore matcher

### PR DESCRIPTION
**Pull request by septs**
```go
matcher := DummyIgnoreMatcher(false) // Always not match (not ignore)
matcher := DummyIgnoreMatcher(true)  // Always match (ignore)
```

### CODE REVIEW

**Comment by monochromegane** [comment]
Thank you for your Pull Request.
In Go way, we should check the error before using the return value.
I think that this code will trigger bugs like a matching (or not matching) always without noticing the error.

**Comment by septs** [comment]
@monochromegane 

When the user does not configure `gitignore`:

```
if unset gitignore then
   allow files
else
   use gitignore
end
```

**Comment by septs** [comment]
fixing

**Comment by monochromegane** [comment]
Thank you.
I understood your suggestion.
Even so, the users might not be able to predict default matcher behavior when an error occurred.

So, your new suggestion is good.
Because the users can choose whether to use the dummy matcher.

**Comment by septs** [comment]
Can it be merged?

Thanks

**Comment by monochromegane** [comment]
Thanks.

**Pull request merged**
